---
- name: make configuration directory
  file:
    state: directory
    recurse: false
    path: "/etc/docker-services"
    owner: root
    group: root
    mode: 0644

- name: "install {{ container_name }} container script"
  template:
    src: container-mgmt.sh
    dest: "/etc/docker-services/{{ container_name }}"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  notify:
  - "restart {{ container_service_name }}"

- name: install service file
  template:
    src: service.j2
    dest: /etc/systemd/system/{{ container_service_name }}.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify:
  - "restart {{ container_service_name }}"

- name: pull service image
  docker_image:
    name: "{{ container_image }}"
