---

- name: start service
  systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: "{{ container_service_name }}"
  listen: "start {{ container_service_name }}"

- name: stop service
  systemd:
    state: stopped
    name: "{{ container_service_name }}"
  listen: "stop {{ container_service_name }}"

- name: restart service
  systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: "{{ container_service_name }}"
  listen: "restart {{ container_service_name }}"