galaxy_info:
  author: Jesper W. Devantier
  description: creates docker volumes conditionally
  license: MIT
  min_ansible_version: 2.5
  galaxy_tags: []

dependencies:
- role: docker
- role: docker-vol-create
  volumes:
  - "{{ eth_chain_db_volname }}"
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.