---

- name: install UFW
  apt:
    package: ufw
    state: present
    cache_valid_time: 3600

- name: configure UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items: "{{ ufw_policies }}"
  notify:
    - restart ufw

- name: enable UFW logging
  ufw:
    logging: true
  notify:
    - restart ufw

- name: enable SSH with UFW
  ufw:
    rule: limit
    port: "{{ ssh_port }}"
    proto: tcp
  notify:
    - restart ufw

- name: enable ufw
  ufw:
    state: enabled

- set_fact:
    ufw_enabled: true