---

- name: "start {{ container_service_name }}"
  systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: "{{ container_service_name }}"

- name: "stop {{ container_service_name }}"
  systemd:
    state: stopped
    name: "{{ container_service_name }}"

- name: "restart {{ container_service_name }}"
  systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: "{{ container_service_name }}"