
- name: Install requirements
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - python3-pip

- name: Add repo key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present

- name: Add Docker Repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install docker
  apt:
    pkg: docker-ce
    update_cache: true
    state: present
    force: true
  notify: "restart docker service"

- name: Install python library for managing docker (Ansible)
  pip:
    name: docker