---

- name: start seafile
  systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: seafile
  listen: "start seafile"

- name: stop seafile
  systemd:
    state: stopped
    name: seafile
  listen: "stop seafile"

- name: restart seafile
  systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: seafile
  listen: "restart seafile"